### ISSUE TITLE
paroller install question

### ISSUE THREAD

**Issue by jough74** [tgomilar/paroller.js#1]
I've got paroller working on my site, but only if I set data-paroller-type="foreground".  If dont set type (default) or set to "background" nothing happens. Any suggestions?

**Comment by tgomilar** [comment]
Hey,
to set paroller.js parallax effect on any element (background or foreground) you must add **data-paroller-factor** attribute. If there is **no data-paroller-factor**, there will be **no effect**. If data-paroller-factor="" is empty, the default value is 0.

**If you want to use parallax effect on background you must **add CSS background property on** element**.  Below is an example using inline CSS. In these case you don't need to add data-paroller-type attribute because its default value is already background. If you want to set direction to horizontal add data-paroller-direction="horizontal", if not you don't need to add data-paroller-direction attribute because its default value is already set to vertical.

`<div class="background-paroller" style="background: url("my-background.png") center;" data-paroller-factor="0.5">My Content </div>`

**Comment by jough74** [comment]
Thanks for the quick reply!

Yes, all my elements that I want to add parallax to have data-paroller-factor. What I was missing was the fact that for data-paroller-background to work I needed to first add the css background property. I was thinking foreground vs background were functioning like z-index, which is not the case, and was trying to give the -type="background" to things other than images . Got it now. Thanks!

(Thanks too for creating this plugin. I love it. After experimenting with many other ways to add parallax to elements, your solution delivers exactly what I was looking for.)
