### ISSUE TITLE
Is it possible to run the script without the data-paroller-factor attribute?

### ISSUE THREAD

**Issue by Alecto** [tgomilar/paroller.js#15]
I need to set the parallax effect for the block (created in the page builder), in the settings of which it is not possible to add additional attributes.

Can I somehow make the script work using only the class?

**Comment by tobiasvielmetter** [comment]
I have the same issue. I am using a page builder in wordpress (Divi) that does not allow to add data attributes. Adding data attributes with jQuery does not seem to be recognised by the plugin. When I add a custom div with the data attributes already in there it works fine.
It would be great to initialise the plugin just by class or id instead of needing to add the data attribute. This would also make sense, as the data attribute setting can be defined in the initialisation, if I understand this right.

**Comment by powerbuoy** [comment]
Support added in this PR: https://github.com/tgomilar/paroller.js/pull/18

**Comment by tgomilar** [comment]
Solved with Create a PR: #18. Checkout latest release: https://github.com/tgomilar/paroller.js/releases/tag/v1.3.0

Thanks to @powerbuoy 😃
